services:
  postgres:
    image: postgres
    container_name: money-track-api
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: money-track-app
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
